apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluentd
  namespace: kube-logging
  labels:
    app: fluentd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluentd
  labels:
    app: fluentd
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - namespaces
  verbs:
  - get
  - list
  - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fluentd
roleRef:
  kind: ClusterRole
  name: fluentd
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: fluentd
  namespace: kube-logging
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: kube-logging
  labels:
    app: fluentd
spec:
  selector:
    matchLabels:
      app: fluentd
  template:
    metadata:
      labels:
        app: fluentd
    spec:
      serviceAccount: fluentd
      serviceAccountName: fluentd
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: fluentd
        image: fluent/fluentd-kubernetes-daemonset:v1.4.2-debian-elasticsearch-1.1
        env:
          - name:  FLUENT_ELASTICSEARCH_HOST
            value: "10.0.0.0"
          - name:  FLUENT_ELASTICSEARCH_PORT
            value: "9200"
          # - name: FLUENT_ELASTICSEARCH_USER
          #   value: "user"
          # - name: FLUENT_ELASTICSEARCH_PASSWORD
          #   value: "password"
          - name: FLUENT_ELASTICSEARCH_SCHEME
            value: "http"
          - name: FLUENTD_SYSTEMD_CONF
            value: disable
            #          - name: FLUENTD_FLUSH_THREAD_COUNT
            #            value: "8"
            #          - name: FLUENTD_FLUSH_INTERVAL
            #            value: "1s"
            #          - name: FLUENTD_CHUNK_LIMIT_SIZE
            #            value: "10M"
            #          - name: FLUENTD_QUEUE_LIMIT_LENGTH
            #            value: "16"
            #          - name: FLUENTD_RETRY_MAX_INTERVAL
            #            value: "30"
          - name: FLUENTD_RETRY_FOREVER
            value: "true"
          # - name: FLUENT_ELASTICSEARCH_SSL_VERIFY
          #   value: "true"
          # - name: FLUENT_ELASTICSEARCH_SSL_VERSION
          #   value: "TLSv1_2"
          - name: FLUENT_CONTAINER_TAIL_EXCLUDE_PATH
            value: /var/log/containers/fluent*
          - name: FLUENT_CONTAINER_TAIL_PARSER_TYPE
            value: /^(?<time>.+) (?<stream>stdout|stderr)( (?<logtag>.))? (?<log>.*)$/
        resources:
          limits:
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        # - name: ssl
        #   mountPath: /fluent-tls/ssl
        #   readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      # - name: ssl
      #   secret:
      #     secretName: fluent-tls

